---
name: gt
channels:
  - pytorch
  - conda-forge
  - pyg 
  - nodefaults
  - nvidia
dependencies:
  - python =3.8
  # additional dependencies
  - numpy =<1.20 # numpy version lock, crucial for MLops packages installed via poetry 
  - libcurl # avoid issues with libcurl version mismatch
  # pytorch
  - pytorch =1.13.1
  - cudatoolkit =11.7
  - torchvision =0.14.1
  - torchaudio =0.13.1
  - pyg =2.3.0
  # utilities
  - pip
  - pip:
      - poetry
