name: lsfml
channels:
  - rdkit
  - defaults
dependencies:
  - joblib=1.0.1
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.5.1
  - pip=20.2.4
  - python=3.7.4
  - rdkit=2020.03.3.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - tqdm=4.51.0
  - ipython
  - xlsxwriter=3.0.2
  - pip:
    - ase==3.21.1
    - einops==0.3.0
    - networkx==2.5
    - numba==0.52.0
    - wandb==0.10.22
    - h5py==3.6.0